---
packages:
  board_base: !include base.yaml
  mcu: !include ../../../mcu/espressif/esp32-s3/arduino.yaml

esphome:
  libraries:
    - "Wire"
    - "SPI"
    - "SensorLib@0.2.1"

external_components:
- source: github://dala318/esphome-qmi8658

sensor:
  - platform: qmi8658
    address: 0x6B
    # interrupt_pin_1: GPIO10
    # interrupt_pin_2: GPIO13       # Warning! Activating this with debug logging may kill your prompt ;)
    # acceleration_range: 4g
    # acceleration_odr: 100hz
    acceleration_x:
      name: "QMI8658 Acceleration X"
    acceleration_y:
      name: "QMI8658 Acceleration Y"
    acceleration_z:
      name: "QMI8658 Acceleration Z"
    gyroscope_x:
      name: "QMI8658 Gyro X"
    gyroscope_y:
      name: "QMI8658 Gyro Y"
    gyroscope_z:
      name: "QMI8658 Gyro Z"
    temperature:
      name: "QMI8658 Temperature"
      filters:
        - offset: 34.0
    update_interval: 5s