---
psram:
  mode: octal
  speed: 80MHz

esp32:
  board: adafruit_matrixportal_esp32s3

substitutions:
  framework: espidf  # arduino | espidf — overridable per instance

packages:
  mcu: !include ../../../mcu/espressif/esp32-s3/${framework}.yaml
  base: !include ../../../base.yaml
  extended: !include ../../../extended.yaml