---
esp32:
  flash_size: 32MB
  cpu_frequency: 240MHZ
  framework:
    advanced:
      # Required for OTA with 32MB flash since 2026.8
      enable_idf_experimental_features: true

psram:
  mode: octal
  speed: 80MHz

esphome:
  platformio_options:
    board_build.flash_mode: qio
  on_boot:
    - priority: 600
      then:
        #- output.turn_on: pin_power_sdcard
        # - output.turn_on: pin_power_lcd
        # - output.turn_on: pin_power_codec_pa
        # - output.turn_on: pin_power_bat_adc
        # - output.turn_on: pin_power_system
        - lvgl.widget.hide: boot_screen
        #- output.turn_on: pin_power_aichip
        #- output.turn_on: pin_power_grove
        
packages:
  base: !include ../../../base.yaml
  extended: !include ../../../extended.yaml

uart:
  - id: uart_0
    tx_pin: GPIO43
    rx_pin: GPIO44
    baud_rate: 115200

logger:
  hardware_uart: UART0

i2c:
  - id: i2c_0
    scl: GPIO48
    sda: GPIO47
    frequency: 400kHz
    setup_priority: 1000

  - id: i2c_1
    scl: GPIO38
    sda: GPIO39
    frequency: 400kHz
    setup_priority: 950

spi:
  - id: spi_2
    clk_pin: GPIO4
    mosi_pin: GPIO5
    miso_pin: GPIO6
    
  - id: spi_3
    clk_pin: GPIO7
    type: quad
    data_pins:
      - GPIO9
      - GPIO1
      - GPIO14
      - GPIO13

tca9555:
  - id: io_expander
    i2c_id: i2c_0

# power_supply:
#   - id: pin_8
#     enable_on_boot: true
#     setup_priority: 998
#     pin:
#       tca9555: io_expander
#       number: 8
#   - id: pin_9
#     enable_on_boot: true
#     setup_priority: 997
#     pin:
#       tca9555: io_expander
#       number: 9
#   - id: pin_10
#     enable_on_boot: true
#     setup_priority: 996
#     pin:
#       tca9555: io_expander
#       number: 10
#   - id: pin_11
#     enable_on_boot: true
#     setup_priority: 995
#     pin:
#       tca9555: io_expander
#       number: 11
#   - id: pin_12
#     enable_on_boot: true
#     setup_priority: 994
#     pin:
#       tca9555: io_expander
#       number: 12
#   - id: pin_14
#     enable_on_boot: true
#     setup_priority: 993
#     pin:
#       tca9555: io_expander
#       number: 14
#   - id: pin_15
#     enable_on_boot: true
#     setup_priority: 992
#     pin:
#       tca9555: io_expander
#       number: 15

# ### SDCARD Support - DISABLED ###

# # external_components:
# #   - source: github://n-serrette/esphome_sd_card
# #     components: [ sd_mmc_card, sd_file_server ]

# # sd_mmc_card:
# #   id: sd_0
# #   mode_1bit: true
# #   clk_pin: GPIO4
# #   cmd_pin: GPIO5
# #   data0_pin: GPIO6

time:
  - platform: pcf8563
    id: pcf8563_time
    address: 0x51
    i2c_id: i2c_0
    update_interval: never
  - id: !extend homeassistant_time
    on_time_sync:
      then:
        pcf8563.write_time:
          id: pcf8563_time

sensor:
  - id: rotary_0
    platform: rotary_encoder
    name: "Rotary Encoder"
    pin_a: GPIO41
    pin_b: GPIO42
    on_clockwise: 
      then:
        lvgl.page.next:
    on_anticlockwise: 
      then:
        lvgl.page.previous:
  - platform: adc
    pin: 
      number: GPIO3
      ignore_strapping_warning: true
    name: "Battery Voltage"
    id: battery_voltage
    attenuation: 2.5db
    update_interval: 1s
    accuracy_decimals: 4
    filters:
      - multiply: 4.1  # Adjust based on voltage divider (see note below)
    unit_of_measurement: "V"

binary_sensor:
  - id: rotary_button
    platform: gpio
    pin:
      tca9555: io_expander
      number: 3
      inverted: true
    name: "Rotary Encoder Button"
    on_press:
      - voice_assistant.start:
          silence_detection: false
    on_release:
      - voice_assistant.stop:


light:
  - id: led_0
    platform: esp32_rmt_led_strip
    rgb_order: GRB
    pin: GPIO40
    num_leds: 1
    chipset: ws2812
    name: "RGB LED"



micro_wake_word:
  id: micro_wake_word_0
  microphone:
    microphone: mic_0
  vad:
    model: github://esphome/micro-wake-word-models/models/v2/vad.json@main
  models:
    - model: github://esphome/micro-wake-word-models/models/v2/hey_jarvis.json@main


