---
esphome:
  platformio_options:
    board_build.flash_mode: dio

esp32:
  flash_size: 16MB

psram:
  mode: quad
  speed: 40MHz

packages:
  display: !include ../../component/display/waveshare_esp32-s3-geek.yaml
  base: !include ../../base.yaml
  extended: !include ../../extended.yaml
