---
substitutions:
  framework: espidf  # arduino | espidf — overridable per instance

packages:
  mcu: !include ../../../mcu/espressif/esp32-s3/${framework}.yaml
  base: !include ../../../base.yaml
  extended: !include ../../../extended.yaml
  display: !include ../../../component/display/waveshare-esp32-s3-lcd-4.3.yaml

esphome:
  platformio_options:
    board_build.flash_mode: dio

esp32:
  flash_size: 16MB

psram:
  mode: quad
  speed: 40MHz
