---
substitutions:
  framework: espidf  # arduino | espidf — overridable per instance

packages:
  board: !include ../../board/lilygo/t7_s3/base.yaml
  bt_proxy: !include ../../component/bluetooth/proxy_${framework}.yaml
  sen55: !include
    file: ../../component/sensor/sen55.yaml
    vars:
      i2c_sda_pin: GPIO13
      i2c_scl_pin: GPIO12
      i2c_scan: False
      i2c_frequency: 800kHz
  display: !include ../../component/display/aqm_display.yaml
  ui: !include ../../ui/ui_128_128_aqm.yaml

i2c:
  sda: GPIO13
  scl: GPIO12
  scan: true
  id: bus_a
  frequency: 800kHz
