---
substitutions:
  framework: espidf  # arduino | espidf — overridable per instance

packages:
  board: !include ../../board/waveshare/s3-matrix/${framework}.yaml
  bt_proxy: !include ../../component/bluetooth/proxy_${framework}.yaml
  ld2450: !include 
    file: ../../component/sensor/ld2450.yaml
    vars:
      uart_tx: GPIO33
      uart_rx: GPIO34