---
substitutions:
  framework: espidf  # arduino | espidf — overridable per instance

packages:
  board: !include ../../board/waveshare/s3-zero/base.yaml
  bt_proxy: !include ../../component/bluetooth/proxy_${framework}.yaml
  ld2450: !include ../../component/sensor/ld2450.yaml