---
packages:
  board: !include ../../board/tuya/sk20.yaml
  bt_proxy: !include ../../component/bluetooth/proxy_bk72xx.yaml
  galaxy_projector: !include
    file: ../../component/light/sk20_galaxy.yaml
    vars:
      galaxy_red_pwm: galaxy_red_pwm
      galaxy_green_pwm: galaxy_green_pwm
      galaxy_blue_pwm: galaxy_blue_pwm
  
  laser_projector: !include
    file:  ../../component/light/sk20_laser.yaml
    vars:
      laser_pwm: laser_pwm

  projector_motor: !include
    file: ../../component/light/sk20_motor.yaml
    vars:
      motor_pwm: motor_pwm

output:
  - platform: libretiny_pwm
    id: galaxy_red_pwm
    pin: 
      number: P9
      inverted: true
      mode:
        open_drain: True
        output: True

  - platform: libretiny_pwm
    id: galaxy_green_pwm
    pin: 
      number: P24
      inverted: True
      mode:
        open_drain: True
        output: True

  - platform: libretiny_pwm
    id: galaxy_blue_pwm
    pin: 
      number: P26
      inverted: True
      mode:
        open_drain: True
        output: True

  - platform: libretiny_pwm
    id: laser_pwm
    pin: 
      number: P8
      inverted: True
      mode:
        open_drain: True
        output: True

  - platform: libretiny_pwm
    id: motor_pwm
    min_power: 20%
    pin: 
      number: P6

  - platform: gpio
    id: button_led0_gpio
    pin: 
      number: P1
      inverted: true

  - platform: libretiny_pwm
    id: button_led1_pwm
    pin: 
      number: P7
      inverted: true

binary_sensor:
  - platform: gpio
    pin: 
      number: P14
      mode: INPUT_PULLDOWN_16
      inverted: true
    name: Button
    on_press: 
      then:
        - light.toggle: rgb_light

light:
  - platform: binary
    name: bled
    id: bled
    output: button_led0_gpio
    restore_mode: ALWAYS_OFF
    internal: true

  - platform: monochromatic
    name: rled
    id: rled
    output: button_led1_pwm
    restore_mode: ALWAYS_OFF
    internal: true

wifi:
  on_connect:
    light.turn_on: bled
  on_disconnect:
    light.turn_off: bled

api:
  on_client_connected:
    if:
      condition:
        api.connected:
      then:
        - light.turn_on: rled
      else:
        - light.turn_off: rled
  on_client_disconnected:
    if:
      condition:
        api.connected:
      then:
        - light.turn_on: rled
      else:
        - light.turn_off: rled