---
substitutions:
  framework: espidf  # arduino | espidf — overridable per instance

packages:
  board: !include ../../board/waveshare/s3-lcd-touch-1.85c/base.yaml
  bt_proxy: !include ../../component/bluetooth/proxy_${framework}.yaml