---
packages:
  mcu: !include ../../../mcu/espressif/esp32-s3/${framework}.yaml
  base: !include ../../../base.yaml
  extended: !include ../../../extended.yaml

esp32:
  board: esp32-s3-devkitc-1
  cpu_frequency: 240MHz
  flash_size: 8MB
  framework:
    sdkconfig_options:
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"
      CONFIG_ESP32S3_INSTRUCTION_CACHE_32KB: "y"

      # Moves instructions and read only data from flash into PSRAM on boot.
      # Both enabled allows instructions to execute while a flash operation is in progress without needing to be placed in IRAM.
      # Considerably speeds up mWW at the cost of using more PSRAM.
      CONFIG_SPIRAM_RODATA: "y"
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: "y"

      CONFIG_BT_ALLOCATION_FROM_SPIRAM_FIRST: "y"
      CONFIG_BT_BLE_DYNAMIC_ENV_MEMORY: "y"

      CONFIG_MBEDTLS_EXTERNAL_MEM_ALLOC: "y"
      CONFIG_MBEDTLS_SSL_PROTO_TLS1_3: "y"  # TLS1.3 support isn't enabled by default in IDF 5.1.5

# esphome:
#   platformio_options:
#     build_flags: -DBOARD_HAS_PSRAM
#     board_build.arduino.memory_type: qio_opi
#     board_build.f_flash: 80000000L
#     board_build.flash_mode: qio 

psram:
  mode: octal
  speed: 80MHz

i2c:
  - id: internal_i2c
    sda: GPIO5
    scl: GPIO6
    frequency: 400kHz
