---
substitutions:
  framework: espidf  # arduino | espidf — overridable per instance

packages:
  mcu: !include ../../../mcu/espressif/esp32/${framework}.yaml
  base: !include ../../../base.yaml
  extended: !include ../../../extended.yaml

esp32:
  board: m5stack-atom
  cpu_frequency: 240MHz
